// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Serene Heart
 * {1}{G}
 * Instant
 * Destroy all Auras.
 */
val SereneHeart = card("Serene Heart") {
    manaCost = "{1}{G}"
    colorIdentity = "G"
    typeLine = "Instant"
    oracleText = "Destroy all Auras."
    spell {
        effect = Effects.ForEachInGroup(
            GroupFilter(GameObjectFilter.Permanent),
            Effects.Move(EffectTarget.Self, Zone.GRAVEYARD, byDestruction = true),
            noRegenerate = false
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "242"
        artist = "D. Alexander Gregory"
        flavorText = "\"If magic is your crutch, cast it aside and learn to walk without it.\"\n—Teferi"
        imageUri = "https://cards.scryfall.io/normal/front/a/f/aff19d9d-8069-4f8d-a81b-e2fcd94c13b3.jpg"
    }
}
