// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.khc.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.EffectTarget
import com.wingedsheep.sdk.scripting.values.ContextPropertyKey
import com.wingedsheep.sdk.scripting.values.DynamicAmount


/**
 * Lathril, Blade of the Elves
 * {2}{B}{G}
 * Legendary Creature — Elf Noble
 * 2/3
 * Menace (This creature can't be blocked except by two or more creatures.)
 * Whenever Lathril deals combat damage to a player, create that many 1/1 green Elf Warrior creature tokens.
 * {T}, Tap ten untapped Elves you control: Each opponent loses 10 life and you gain 10 life.
 */
val LathrilBladeOfTheElves = card("Lathril, Blade of the Elves") {
    manaCost = "{2}{B}{G}"
    colorIdentity = "BG"
    typeLine = "Legendary Creature — Elf Noble"
    oracleText = "Menace (This creature can't be blocked except by two or more creatures.)\nWhenever Lathril deals combat damage to a player, create that many 1/1 green Elf Warrior creature tokens.\n{T}, Tap ten untapped Elves you control: Each opponent loses 10 life and you gain 10 life."
    power = 2
    toughness = 3
    keywords(Keyword.MENACE)
    triggeredAbility {
        trigger = Triggers.DealsCombatDamageToPlayer
        effect = Effects.CreateToken(
            count = DynamicAmount.ContextProperty(ContextPropertyKey.TRIGGER_DAMAGE_AMOUNT),
            power = 1,
            toughness = 1,
            colors = setOf(Color.GREEN),
            creatureTypes = setOf("Elf", "Warrior")
        )
    }
    activatedAbility {
        cost = Costs.Composite(Costs.Tap, Costs.TapPermanents(10, GameObjectFilter.Creature.withSubtype("Elf")))
        effect = Effects.Composite(
            Effects.LoseLife(10, EffectTarget.PlayerRef(Player.EachOpponent)),
            GainLifeEffect(10)
        )
    }
    metadata {
        rarity = Rarity.MYTHIC
        collectorNumber = "1"
        artist = "Caroline Gariba"
        imageUri = "https://cards.scryfall.io/normal/front/5/4/547888c3-a9a6-4413-b29a-6bcd8a9279bf.jpg"
    }
}
