-- Richer match-history stats: per-deck colors/sets, game mode, activity measures, and a coarse
-- client-IP capture used for an admin-only geolocation estimate. Like V1 this only runs when accounts
-- are enabled. Per-user stats still filter by user_id; guest seats (user_id null, is_ai false) count
-- toward global admin stats + geolocation but never toward a signed-in user's numbers.

-- match_results: game mode (matchmaking context) + activity measures used by the recording gate and
-- the games-per-day / mode-distribution dashboards.
ALTER TABLE match_results ADD COLUMN game_mode   TEXT;
ALTER TABLE match_results ADD COLUMN frame_count INT NOT NULL DEFAULT 0;
ALTER TABLE match_results ADD COLUMN turn_count  INT NOT NULL DEFAULT 0;

-- Cheap date-bucketed scans for the games-per-day chart.
CREATE INDEX idx_match_results_ended_at ON match_results (ended_at);

-- match_participants: per-seat deck profile + AI flag + raw client IP.
--   colors     - deck color identity, canonical WUBRG order (e.g. 'WU'); empty string = colorless.
--   set_codes  - comma-separated distinct set codes in the deck (e.g. 'DSK,BLB').
--   is_ai      - distinguishes AI seats from guests (both have null user_id).
--   client_ip  - raw connecting IP, admin-only; never sent to clients. Null for AI / unknown.
ALTER TABLE match_participants ADD COLUMN colors    TEXT;
ALTER TABLE match_participants ADD COLUMN set_codes TEXT;
ALTER TABLE match_participants ADD COLUMN is_ai     BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE match_participants ADD COLUMN client_ip TEXT;

-- Each seat's deck contents, one row per distinct card, so we can later compute the most-played
-- cards and per-card win rates (a card's "win rate" = decks containing it that won / decks containing
-- it). Normalized rather than a JSON blob precisely so these aggregates are plain SQL group-bys.
CREATE TABLE match_participant_cards (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id BIGINT NOT NULL REFERENCES match_participants (id) ON DELETE CASCADE,
    card_name      TEXT   NOT NULL,
    copies         INT    NOT NULL
);
CREATE INDEX idx_match_participant_cards_participant ON match_participant_cards (participant_id);
CREATE INDEX idx_match_participant_cards_card ON match_participant_cards (card_name);

-- Finished tournaments + their settings. Like matches, only recorded when at least one seat is a
-- human (AI-only / LLM tournaments are excluded; they also use a separate, unpersisted code path).
CREATE TABLE tournaments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lobby_id        TEXT        NOT NULL,
    name            TEXT,
    format          TEXT,        -- TournamentFormat (SEALED / DRAFT / PREMADE_DECKS / ...)
    game_mode       TEXT,        -- LobbyGameMode (TOURNAMENT / FREE_FOR_ALL / ...)
    set_codes       TEXT,        -- comma-separated set codes the tournament used
    player_count    INT         NOT NULL DEFAULT 0,
    rounds          INT         NOT NULL DEFAULT 0,
    games_per_match INT         NOT NULL DEFAULT 0,
    winner_name     TEXT,
    started_at      TIMESTAMPTZ,
    ended_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_tournaments_ended_at ON tournaments (ended_at);

-- One seat in a finished tournament with its final placement + match record.
CREATE TABLE tournament_participants (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id BIGINT  NOT NULL REFERENCES tournaments (id) ON DELETE CASCADE,
    user_id       BIGINT  REFERENCES users (id) ON DELETE SET NULL,
    player_name   TEXT    NOT NULL,
    is_ai         BOOLEAN NOT NULL DEFAULT false,
    placement     INT     NOT NULL,
    wins          INT     NOT NULL DEFAULT 0,
    losses        INT     NOT NULL DEFAULT 0,
    draws         INT     NOT NULL DEFAULT 0
);
CREATE INDEX idx_tournament_participants_tournament ON tournament_participants (tournament_id);
CREATE INDEX idx_tournament_participants_user ON tournament_participants (user_id);
