-- Ranked play: per-mode ELO ratings for signed-in accounts. Like the other account tables this only
-- runs when accounts are enabled. A "ranked" game is a 1v1 game (standard quick game or a TOURNAMENT-
-- bracket match) where every seat is a logged-in human (no guests, no AI). Each finished ranked game
-- adjusts both players' rating for that game's mode (LIMITED / CONSTRUCTED / COMMANDER) and appends a
-- history row so the dashboard can chart rating over time.

-- Tag the originating game as ranked, so the admin/global views can tell ranked games apart.
ALTER TABLE match_results ADD COLUMN ranked BOOLEAN NOT NULL DEFAULT false;

-- Current rating per (user, mode). A row is created lazily on a user's first ranked game in a mode;
-- a missing row means "unrated" and is treated as the starting rating. games_played drives the
-- provisional placement window (faster rating movement) and the displayed tier.
--   mode         - RankedMode: LIMITED / CONSTRUCTED / COMMANDER.
--   rating       - current ELO (starts at 1500).
--   peak_rating  - highest rating ever reached, for a "career high" display.
CREATE TABLE user_ratings (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT           NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    mode         TEXT             NOT NULL,
    rating       DOUBLE PRECISION NOT NULL DEFAULT 1200,
    games_played INT              NOT NULL DEFAULT 0,
    wins         INT              NOT NULL DEFAULT 0,
    losses       INT              NOT NULL DEFAULT 0,
    draws        INT              NOT NULL DEFAULT 0,
    peak_rating  DOUBLE PRECISION NOT NULL DEFAULT 1200,
    updated_at   TIMESTAMPTZ      NOT NULL DEFAULT now(),
    UNIQUE (user_id, mode)
);
CREATE INDEX idx_user_ratings_user ON user_ratings (user_id);
-- Leaderboard scan per mode.
CREATE INDEX idx_user_ratings_mode_rating ON user_ratings (mode, rating DESC);

-- One row per ranked game per player: the before/after rating and the opponent it was earned against.
-- Backs the dashboard's "rating over time" chart (filter by user_id + mode, order by created_at).
CREATE TABLE rating_history (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT           NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    mode             TEXT             NOT NULL,
    rating_before    DOUBLE PRECISION NOT NULL,
    rating_after     DOUBLE PRECISION NOT NULL,
    delta            DOUBLE PRECISION NOT NULL,
    result           TEXT             NOT NULL,        -- WIN / LOSS / DRAW
    opponent_user_id BIGINT           REFERENCES users (id) ON DELETE SET NULL,
    opponent_rating  DOUBLE PRECISION,
    game_id          TEXT,
    created_at       TIMESTAMPTZ      NOT NULL DEFAULT now()
);
CREATE INDEX idx_rating_history_user_mode ON rating_history (user_id, mode, created_at);
