-- Durable, compact game replays. The engine is deterministic, so a whole game is reproducible from
-- its setup (RNG seed + decks + seat ids) plus the ordered input stream; we persist that instead of
-- megabytes of per-frame snapshots. `data` is the gzip+base64-encoded CompactReplay JSON — typically
-- a few KB per game. Like the rest of the accounts subsystem this migration only runs when accounts
-- are enabled. Keyed by game_id (the same id used by the live cache and the public /replay links);
-- a user's own replays are found by joining match_results/match_participants on game_id.
CREATE TABLE game_replays (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id         TEXT        NOT NULL UNIQUE,
    format          TEXT,
    winner_name     TEXT,
    tournament_name TEXT,
    started_at      TIMESTAMPTZ,
    ended_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    frame_count     INT         NOT NULL DEFAULT 0,
    player_names    TEXT        NOT NULL DEFAULT '',
    data            TEXT        NOT NULL
);
CREATE INDEX idx_game_replays_game_id ON game_replays (game_id);
CREATE INDEX idx_game_replays_ended_at ON game_replays (ended_at);
