// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.bro.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.DealDamageEffect
import com.wingedsheep.sdk.scripting.effects.GainLifeEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetCreature


/**
 * Deadly Riposte
 * {1}{W}
 * Instant
 * Deadly Riposte deals 3 damage to target tapped creature and you gain 2 life.
 */
val DeadlyRiposte = card("Deadly Riposte") {
    manaCost = "{1}{W}"
    colorIdentity = "W"
    typeLine = "Instant"
    oracleText = "Deadly Riposte deals 3 damage to target tapped creature and you gain 2 life."
    spell {
        val t = target("target", TargetCreature(filter = TargetFilter.Creature.tapped()))
        effect = Effects.Composite(
            DealDamageEffect(3, t),
            GainLifeEffect(3)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "5"
        artist = "Olena Richards"
        flavorText = "\"Automatons are fast, precise, and tireless, but they all share one weakness: predictability. Learn their patterns. Strike when they're vulnerable.\"\n—Horance, Urzan general"
        imageUri = "https://cards.scryfall.io/normal/front/3/8/38eca0ae-d400-4afb-9a45-7100f4cd7149.jpg"
    }
}
